# Generated by Django 5.2.12 on 2026-03-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='histogram',
            field=models.CharField(default=''),
        ),
    ]
